export const RESOURCES = [
  {
    name: "Introduction to Information Retrieval",
    type: "Book",
    link: "https://nlp.stanford.edu/IR-book/pdf/irbookonlinereading.pdf",
    author: "Christopher Manning, Prabhakar Raghavan, Hinrich Schütze",
  },
  {
    name: "Designing Data-Intensive Applications",
    type: "Book",
    link: "https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321",
    author: "Martin Kleppmann",
  },
  {
    name: "Curated Engineering Blog Posts",
    type: "Blog Post",
    link: "https://www.linkedin.com/posts/ryanlpeterman_19-vetted-company-engineering-blog-posts-activity-7138557807481475072-FX9U",
    author: "Ryan Peterman",
  },
  {
    name: "Database Internals",
    type: "Book",
    link: "https://www.oreilly.com/library/view/database-internals/9781492040330/",
    author: "Alex Petrov",
  },
  {
    name: "Machine Learning Engineering Open Book",
    type: "Book",
    link: "https://github.com/stas00/ml-engineering",
    author: "Stas Bekman",
  },
  {
    name: "Engineering MLOps",
    type: "Book",
    link: "https://www.oreilly.com/library/view/engineering-mlops/9781800562882/",
    author: "Emmanuel Raj",
  },
  {
    name: "Professional Programming",
    type: "Resources",
    link: "https://github.com/charlax/professional-programming",
    author: "Charles-Axel Dein",
  },
  {
    name: "Eugene Yan: ML Ops",
    type: "Blog",
    link: "https://eugeneyan.com/start-here/",
    author: "Eugene Yan",
  },
  {
    name: "Explaining The Postgres Meme",
    type: "Blog Post",
    link: "https://avestura.dev/blog/explaining-the-postgres-meme",
    author: "Aryan Ebrahimpour",
  },
  {
    name: "CMU Database Group",
    type: "Youtube Channel",
    link: "https://www.youtube.com/@CMUDatabaseGroup/videos",
    author: "CMU Database Group",
  },
  {
    name: "MIT 6.824 Distributed Systems (Spring 2020)",
    type: "Playlist",
    link: "https://www.youtube.com/playlist?list=PLrw6a1wE39_tb2fErI4-WkMbsvGQk9_UB",
    author: "MIT",
  },
  {
    name: "Fullstack React GraphQL TypeScript Tutorial",
    type: "Video",
    link: "https://www.youtube.com/watch?v=I6ypD7qv3Z8",
    author: "Ben Awad",
  },
  {
    name: "Lessons from building GitHub code search",
    type: "Video",
    link: "https://www.youtube.com/watch?v=CqZA_KmygKw",
    author: "GitHub",
  },
  {
    name: "Building Secure and Reliable Systems",
    type: "Video",
    link: "https://google.github.io/building-secure-and-reliable-systems/raw/toc.html",
    author: "Google",
  },
  {
    name: "Practical Deep Learning",
    type: "Course",
    link: "https://course.fast.ai/",
    author: "Jeremy Howard",
  },
  {
    name: "The Complete History & Strategy of Visa",
    type: "Podcast",
    link: "https://www.acquired.fm/episodes/visa",
    author: "Ben Gilbert and David Rosenthal",
  },
  {
    name: "Production Prolog",
    type: "Video",
    link: "https://www.youtube.com/watch?v=G_eYTctGZw8",
    author: "Michael Hendricks",
  },
];
